name: Build Windows EXE (Electron)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022   # stabilny runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18 (stabilne z electron-builder 24)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Fix na "ERR_ELECTRON_BUILDER_CANNOT_EXECUTE" – czyścimy cache buildera
      - name: Clear electron-builder cache
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force "$env:LOCALAPPDATA\electron-builder" -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force "$env:USERPROFILE\.cache\electron-builder" -ErrorAction SilentlyContinue

      # NSIS bywa wymagany na Windows – doinstalujmy go z Chocolatey
      - name: Install NSIS
        run: choco install nsis -y

      - name: Install deps
        run: npm install --legacy-peer-deps

      - name: Build EXE (NSIS)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win nsis --publish never

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rejestr-Nadgodzin-Windows-EXE
          path: dist/*.exe
