name: Build Windows EXE (Electron)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Oficjalny obraz electron-builder z Wine do budowy Windows EXE na Linuksie
    container: electronuserland/builder:wine

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: |
          npm ci || npm install --no-audit --no-fund --legacy-peer-deps

      # Budowa instalatora .exe (NSIS) bez publikacji do Releases
      - name: Build EXE (NSIS)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win nsis --publish never

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rejestr-Nadgodzin-Windows-EXE
          path: dist/*.exe
